import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

/**
 * Builds public CSS assets for `@admiral-ds/admiral3-tokens`.
 *
 * The script turns structured token objects from `src/css-data.ts` into CSS
 * custom properties under `dist/css`. It is used by `npm run build` and is also
 * imported by unit tests, so the file is split into pure transformation helpers
 * and a small filesystem write step.
 *
 * Output contract:
 * - every public variable starts with `--admiral`;
 * - generated files always include `header`;
 * - `index.css` contains global colors, all themes, radius, typography and static utility tokens;
 * - `themes.css` contains all theme color variables and shadow geometry;
 * - standalone `shadow.css` includes light-theme fallbacks for shadow colors;
 * - per-theme files scope one selected theme to `:root`.
 *
 * `src/css-data.ts` is intentionally the only imported token aggregation point.
 * It keeps CSS generation internal and avoids publishing source token maps as a
 * package subpath.
 */
import {
  animation,
  breakpoints,
  globalColors,
  radius,
  shadow,
  textStyles,
  themeModes,
  themes,
  typographyPrimitives,
  zIndex,
} from '../src/css-data';
import { resolveGlobalColorValue, type TokenValue } from '../src/tokens/color/resolveGlobalColorReference';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, '..');
const distDir = resolve(rootDir, 'dist');
const cssDir = resolve(distDir, 'css');

/**
 * Public CSS variable prefix.
 *
 * Consumers may override these variables directly, so changing this value is a
 * breaking CSS API change.
 */
const cssPrefix = '--admiral';

const header = ['/*', ' * This file is generated by script.', ' * Do not edit it manually.', ' */', ''].join('\n');

type TokenRecord = {
  readonly [key: string]: TokenRecord | TokenValue;
};
type VariableEntry = readonly [name: string, value: TokenValue];
type ThemeMode = (typeof themeModes)[number];
type CssFiles = Record<string, string>;
type ThemeVariablesByMode = Record<ThemeMode, VariableEntry[]>;
type GeneratedCssParts = {
  readonly globalColorsCss: string;
  readonly animationCss: string;
  readonly breakpointsCss: string;
  readonly radiusCss: string;
  readonly typographyCss: string;
  readonly shadowCss: string;
  readonly zIndexCss: string;
  readonly themesCss: string;
  readonly themeFiles: CssFiles;
};

/**
 * Converts a token path segment into the naming style used by CSS variables.
 *
 * Token objects use camelCase keys and sometimes numeric string keys. CSS
 * custom properties use lowercase kebab-case segments.
 */
export const toKebab = (value: string | number) =>
  String(value)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/_/g, '-')
    .toLowerCase();

/**
 * Builds a public CSS custom property name from token path segments.
 *
 * @example
 * toVarName(['color', 'text', 'neutral', 'text1', 'rest']);
 * // '--admiral-color-text-neutral-text1-rest'
 */
export const toVarName = (parts: readonly (string | number)[]) => [cssPrefix, ...parts.map(toKebab)].join('-');

/**
 * Checks whether a value should be traversed as a nested token object.
 *
 * Arrays are leaf values here. Shadow tokens are arrays of layers and must not
 * be flattened as generic object records.
 */
const isRecord = (value: unknown): value is TokenRecord =>
  value !== null && typeof value === 'object' && !Array.isArray(value);

/**
 * Converts a nested token object into `[path, value]` pairs.
 *
 * Each leaf pair later becomes exactly one CSS custom property.
 */
export const flatten = (value: TokenRecord | TokenValue, path: readonly string[] = []): [string[], TokenValue][] => {
  if (!isRecord(value)) {
    return [[Array.from(path), value]];
  }

  return Object.entries(value).flatMap(([key, nestedValue]) => {
    return flatten(nestedValue, [...path, key]);
  });
};

/**
 * Converts a global color token reference into a CSS variable reference.
 *
 * Theme color maps store references such as `primary.primary110`. CSS keeps
 * semantic theme variables connected to global color variables:
 *
 * `var(--admiral-color-global-primary-primary110, #0062FF)`
 *
 * The fallback makes per-theme CSS files usable even when `global-colors.css`
 * was not imported separately.
 */
export const resolveGlobalColorReference = (value: TokenValue): TokenValue => {
  if (typeof value !== 'string') {
    return value;
  }

  const resolvedValue = resolveGlobalColorValue(value);

  if (resolvedValue === value) {
    return value;
  }

  const [group, token] = value.split('.');

  return `var(${toVarName(['color-global', group, token])}, ${resolvedValue})`;
};

const typographyPrimitiveGroupNames = ['fontFamily', 'fontWeight', 'fontSize', 'lineHeight'] as const;

type TypographyPrimitiveGroupName = (typeof typographyPrimitiveGroupNames)[number];

const isTypographyPrimitiveGroupName = (value: string): value is TypographyPrimitiveGroupName =>
  typographyPrimitiveGroupNames.includes(value as TypographyPrimitiveGroupName);

/**
 * Converts typography text style values into primitive variable references.
 *
 * Text styles intentionally point back to primitive scale variables. This keeps
 * custom typography overrides predictable: changing a primitive can cascade to
 * every text style that uses the same primitive value.
 */
export const resolveTypographyPrimitiveReference = (path: readonly string[], value: TokenValue): TokenValue => {
  const propertyName = path[path.length - 1];

  if (!isTypographyPrimitiveGroupName(propertyName)) {
    return value;
  }

  const primitiveGroup = typographyPrimitives[propertyName];
  const primitiveToken = Object.entries(primitiveGroup).find(([, primitiveValue]) => primitiveValue === value);

  if (!primitiveToken) {
    return value;
  }

  const [tokenName] = primitiveToken;

  return `var(${toVarName(['typography-primitives', propertyName, tokenName])}, ${value})`;
};

/**
 * Renders normalized CSS custom property entries.
 */
export const renderVariables = (entries: readonly VariableEntry[], indent = '  ') =>
  entries.map(([name, value]) => `${indent}${name}: ${value};`).join('\n');

/**
 * Wraps CSS custom property entries into a selector block.
 */
export const renderBlock = (selector: string, entries: readonly VariableEntry[]) =>
  `${selector} {\n${renderVariables(entries)}\n}\n`;

/**
 * Adds the generated-file header consistently to every CSS artifact.
 */
const cssFile = (body: string) => `${header}${body.trim()}\n`;

/**
 * Builds CSS variables for token groups represented as one variable per leaf.
 *
 * Theme colors pass `resolveColorReferences: true` because their source values
 * point to global color tokens and should become `var(..., fallback)` references
 * rather than fixed hex/rgba values.
 */
export const buildFlatVariables = (
  scope: string,
  object: TokenRecord,
  { resolveColorReferences = false }: { resolveColorReferences?: boolean } = {},
): VariableEntry[] =>
  flatten(object).map(([path, value]) => [
    toVarName([scope, ...path]),
    resolveColorReferences ? resolveGlobalColorReference(value) : value,
  ]);

/**
 * Builds semantic theme color variables for every supported theme mode.
 *
 * The result is keyed by TypeScript theme mode names (`lightNeutral`) while the
 * CSS selectors and filenames are derived later (`light-neutral`).
 */
const buildThemeVariablesByMode = (): ThemeVariablesByMode =>
  Object.fromEntries(
    themeModes.map((mode) => [
      mode,
      buildFlatVariables('color', themes[mode].color as TokenRecord, { resolveColorReferences: true }),
    ]),
  ) as ThemeVariablesByMode;

export const buildTypographyVariables = (): VariableEntry[] => [
  ...buildFlatVariables('typography-primitives', typographyPrimitives as TokenRecord),
  ...flatten(textStyles as TokenRecord).map(
    ([path, value]): VariableEntry => [
      toVarName(['typography-text-styles', ...path]),
      resolveTypographyPrimitiveReference(path, value),
    ],
  ),
];

type MotionEasingValue = readonly [number, number, number, number];

const isMotionEasingValue = (value: unknown): value is MotionEasingValue =>
  Array.isArray(value) && value.length === 4 && value.every((point) => typeof point === 'number');

export const buildAnimationVariables = (): VariableEntry[] =>
  flatten(animation as unknown as TokenRecord).map(([path, value]) => {
    if (path.includes('duration') && typeof value === 'number') {
      return [toVarName(['animation', ...path]), `${value}ms`];
    }

    if (path.includes('easing') && isMotionEasingValue(value)) {
      return [toVarName(['animation', ...path]), `cubic-bezier(${value.join(', ')})`];
    }

    return [toVarName(['animation', ...path]), value];
  });

/**
 * Resolves the light-theme fallback for a shadow layer color token.
 */
const getLightShadowColorFallback = (color: string) =>
  resolveGlobalColorReference(themes.light.color.shadow[color as keyof typeof themes.light.color.shadow]);

/**
 * Builds shadow geometry variables.
 *
 * Shadow geometry is static, but layer colors are theme-dependent. Shadow CSS
 * therefore references `--admiral-color-shadow-*` variables generated by theme
 * CSS instead of inlining a color.
 *
 * `shadow.css` passes `includeFallback: true` so it can work as a standalone
 * file. Theme files omit fallbacks because they define the color-shadow
 * variables in the same CSS asset.
 */
export const buildShadowVariables = ({
  includeFallback = false,
}: { includeFallback?: boolean } = {}): VariableEntry[] =>
  Object.entries(shadow).map(([name, layers]) => [
    toVarName(['shadow', name]),
    layers
      .map(({ x, y, blur, color }) => {
        const colorVariable = toVarName(['color-shadow', color]);
        const fallback = includeFallback ? `, ${getLightShadowColorFallback(color)}` : '';

        return `${x} ${y} ${blur} var(${colorVariable}${fallback})`;
      })
      .join(', '),
  ]);

/**
 * Converts a TypeScript theme mode into the public CSS filename segment.
 */
export const themeFileName = (mode: ThemeMode) => toKebab(mode);

/**
 * Builds the data-attribute selector used by the combined `themes.css` file.
 */
export const themeSelector = (mode: ThemeMode) => `[data-admiral-theme="${themeFileName(mode)}"]`;

/**
 * Builds `themes.css`.
 *
 * Light is emitted on both `:root` and `[data-admiral-theme="light"]` so the
 * full CSS bundle has a default theme without requiring extra markup. Shadow
 * geometry is emitted once in `:root` because it depends on theme shadow color
 * variables and should be available when `themes.css` is imported alone.
 */
const buildThemesCss = (themeVariablesByMode: ThemeVariablesByMode, themeShadowVariables: readonly VariableEntry[]) => {
  return cssFile(
    [
      renderBlock(':root', themeShadowVariables),
      ...themeModes.map((mode) => {
        const selector = mode === 'light' ? `:root,\n${themeSelector(mode)}` : themeSelector(mode);
        return renderBlock(selector, themeVariablesByMode[mode]);
      }),
    ].join('\n'),
  );
};

/**
 * Builds per-theme CSS assets.
 *
 * Each file is scoped to `:root` because importing one `theme-*.css` file means
 * "make this theme the default for this bundle/application". Shadow geometry is
 * included as well, so a single theme file is enough to use theme-dependent
 * shadows.
 */
const buildPerThemeCssFiles = (
  themeVariablesByMode: ThemeVariablesByMode,
  themeShadowVariables: readonly VariableEntry[],
) => {
  return Object.fromEntries(
    themeModes.map((mode) => [
      `theme-${themeFileName(mode)}.css`,
      cssFile(renderBlock(':root', [...themeVariablesByMode[mode], ...themeShadowVariables])),
    ]),
  );
};

/**
 * Builds `index.css`, the single-file CSS import path.
 *
 * It concatenates the same generated blocks used by smaller subpath CSS files.
 * `shadow.css` is intentionally not concatenated here because shadow geometry
 * is already included through `themes.css`.
 */
const buildIndexCss = ({
  globalColorsCss,
  animationCss,
  breakpointsCss,
  themesCss,
  radiusCss,
  typographyCss,
  zIndexCss,
}: Pick<
  GeneratedCssParts,
  'globalColorsCss' | 'animationCss' | 'breakpointsCss' | 'themesCss' | 'radiusCss' | 'typographyCss' | 'zIndexCss'
>) => {
  return cssFile(
    [
      globalColorsCss.replace(header, '').trim(),
      animationCss.replace(header, '').trim(),
      breakpointsCss.replace(header, '').trim(),
      themesCss.replace(header, '').trim(),
      radiusCss.replace(header, '').trim(),
      typographyCss.replace(header, '').trim(),
      zIndexCss.replace(header, '').trim(),
    ].join('\n\n'),
  );
};

/**
 * Builds named CSS asset bodies before assigning final public filenames.
 *
 * This keeps the generation pipeline explicit:
 * source tokens -> variable entries -> CSS blocks -> file map.
 */
const buildGeneratedCssParts = (): GeneratedCssParts => {
  const themeVariablesByMode = buildThemeVariablesByMode();
  const themeShadowVariables = buildShadowVariables();

  const globalColorsCss = cssFile(
    renderBlock(':root', buildFlatVariables('color-global', globalColors as TokenRecord)),
  );
  const animationCss = cssFile(renderBlock(':root', buildAnimationVariables()));
  const breakpointsCss = cssFile(renderBlock(':root', buildFlatVariables('breakpoints', breakpoints as TokenRecord)));
  const radiusCss = cssFile(renderBlock(':root', buildFlatVariables('radius', radius as TokenRecord)));
  const typographyCss = cssFile(renderBlock(':root', buildTypographyVariables()));
  const shadowCss = cssFile(renderBlock(':root', buildShadowVariables({ includeFallback: true })));
  const zIndexCss = cssFile(renderBlock(':root', buildFlatVariables('z-index', zIndex as TokenRecord)));
  const themesCss = buildThemesCss(themeVariablesByMode, themeShadowVariables);
  const themeFiles = buildPerThemeCssFiles(themeVariablesByMode, themeShadowVariables);

  return {
    globalColorsCss,
    animationCss,
    breakpointsCss,
    radiusCss,
    typographyCss,
    shadowCss,
    zIndexCss,
    themesCss,
    themeFiles,
  };
};

/**
 * Builds every public CSS file in memory.
 *
 * Keeping this transformation pure makes it easy to unit test. Filesystem
 * writes are handled separately by `writeCssFiles`.
 */
export const buildCssFiles = (): CssFiles => {
  const cssParts = buildGeneratedCssParts();
  const {
    globalColorsCss,
    animationCss,
    breakpointsCss,
    radiusCss,
    typographyCss,
    shadowCss,
    zIndexCss,
    themesCss,
    themeFiles,
  } = cssParts;
  const indexCss = buildIndexCss(cssParts);

  return {
    'global-colors.css': globalColorsCss,
    'animation.css': animationCss,
    'breakpoints.css': breakpointsCss,
    'themes.css': themesCss,
    'radius.css': radiusCss,
    'typography.css': typographyCss,
    'shadow.css': shadowCss,
    'z-index.css': zIndexCss,
    'index.css': indexCss,
    ...themeFiles,
  };
};

/**
 * Writes generated CSS files to `dist/css`.
 */
export const writeCssFiles = async (files = buildCssFiles()) => {
  await mkdir(cssDir, { recursive: true });
  await Promise.all(Object.entries(files).map(([fileName, content]) => writeFile(resolve(cssDir, fileName), content)));
};

/**
 * Public build entry used by npm scripts.
 *
 * Tests can import it if they need to exercise the complete write flow.
 */
export const buildCss = async () => {
  const files = buildCssFiles();

  await writeCssFiles(files);

  // eslint-disable-next-line no-console
  console.log(`Generated ${Object.keys(files).length} CSS token files in ${cssDir}`);
};

/**
 * Keeps the module importable in tests without writing files as a side effect.
 *
 * The build only runs when this file is called directly via `tsx`.
 */
const isCli = import.meta.url === pathToFileURL(process.argv[1] ?? '').href;

if (isCli) {
  await buildCss();
}
